-- Generated by scripts/setup_bigquery.py --print-ddl. Replace {project}.{dataset} with `project.dataset`.

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.inventory_items` (
  sku STRING NOT NULL OPTIONS(description="Unique item code"),
  name STRING NOT NULL OPTIONS(description="Display name"),
  category STRING OPTIONS(description="Swag, Signage, Booth, Print"),
  on_hand INT64 NOT NULL OPTIONS(description="Physical units in warehouse")
) OPTIONS(description="Campaign material catalog with physical stock on hand.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.inventory_reservations` (
  reservation_id STRING NOT NULL,
  request_id STRING NOT NULL OPTIONS(description="Campaign request id"),
  sku STRING NOT NULL,
  quantity INT64 NOT NULL,
  status STRING NOT NULL OPTIONS(description="ACTIVE or RELEASED"),
  created_at TIMESTAMP NOT NULL
) OPTIONS(description="Append-only stock reservations per campaign request.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.vendors` (
  vendor_id STRING NOT NULL,
  vendor_name STRING NOT NULL,
  active BOOL NOT NULL OPTIONS(description="Only active vendors are quoted")
) OPTIONS(description="Approved suppliers.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.vendor_catalog` (
  vendor_id STRING NOT NULL,
  sku STRING NOT NULL,
  unit_price FLOAT64 NOT NULL OPTIONS(description="USD per unit"),
  lead_time_days INT64 NOT NULL
) OPTIONS(description="Vendor price list and lead times per SKU.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.campaigns` (
  campaign_id STRING NOT NULL,
  campaign_name STRING NOT NULL,
  event_name STRING OPTIONS(description="Parent event, e.g. Google Next 2027"),
  owner STRING,
  total_budget FLOAT64 NOT NULL OPTIONS(description="USD")
) OPTIONS(description="Marketing campaigns and their approved total budget.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.budget_ledger` (
  entry_id STRING NOT NULL,
  campaign_id STRING NOT NULL,
  request_id STRING NOT NULL OPTIONS(description="BASELINE for seeded opening spend"),
  entry_type STRING NOT NULL OPTIONS(description="COMMIT, RELEASE or SPEND"),
  amount FLOAT64 NOT NULL OPTIONS(description="USD, always positive"),
  approved_by STRING OPTIONS(description="auto-policy, human:<role>, or system"),
  created_at TIMESTAMP NOT NULL
) OPTIONS(description="Append-only budget movements. COMMIT = approved spend, RELEASE = returned, SPEND = already spent.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.approval_policy` (
  tier STRING NOT NULL,
  min_amount FLOAT64 NOT NULL OPTIONS(description="Exclusive lower bound, USD"),
  max_amount FLOAT64 NOT NULL OPTIONS(description="Inclusive upper bound, USD"),
  requires_human BOOL NOT NULL,
  approver_role STRING NOT NULL
) OPTIONS(description="Spend tiers: who must approve an amount. amount > min_amount AND <= max_amount.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.approvers` (
  approver_role STRING NOT NULL OPTIONS(description="Must match approval_policy.approver_role"),
  email STRING NOT NULL,
  active BOOL NOT NULL OPTIONS(description="Only active rows are notified")
) OPTIONS(description="Who is notified (email) when a role must approve. Configured at setup time; edit with SQL.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.campaign_requests` (
  request_id STRING NOT NULL,
  campaign_id STRING NOT NULL,
  summary STRING,
  created_at TIMESTAMP NOT NULL
) OPTIONS(description="Every request registered by the orchestrator.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.purchase_orders` (
  po_number STRING NOT NULL OPTIONS(description="Returned by the integration"),
  request_id STRING NOT NULL,
  campaign_id STRING NOT NULL,
  vendor_id STRING NOT NULL,
  sku STRING NOT NULL,
  quantity INT64 NOT NULL,
  total_amount FLOAT64 NOT NULL OPTIONS(description="USD, computed by the guard, not the model"),
  status STRING NOT NULL OPTIONS(description="CREATED or CANCELLED"),
  integration_execution_id STRING OPTIONS(description="Application Integration execution id"),
  created_at TIMESTAMP NOT NULL
) OPTIONS(description="Purchase orders created through Application Integration.");

CREATE TABLE IF NOT EXISTS `{project}.{dataset}.audit_log` (
  event_id STRING NOT NULL,
  created_at TIMESTAMP NOT NULL,
  request_id STRING,
  actor STRING NOT NULL OPTIONS(description="Agent or human role"),
  action STRING NOT NULL,
  details STRING OPTIONS(description="JSON text")
) OPTIONS(description="Append-only trail of every governed action.");

CREATE OR REPLACE VIEW `{project}.{dataset}.v_inventory_available` AS
SELECT i.sku, i.name, i.category, i.on_hand,
       IFNULL(SUM(IF(r.status = 'ACTIVE', r.quantity, 0)), 0) AS reserved,
       i.on_hand - IFNULL(SUM(IF(r.status = 'ACTIVE', r.quantity, 0)), 0) AS free
FROM `{project}.{dataset}.inventory_items` i
LEFT JOIN `{project}.{dataset}.inventory_reservations` r USING (sku)
GROUP BY i.sku, i.name, i.category, i.on_hand
;

CREATE OR REPLACE VIEW `{project}.{dataset}.v_campaign_budget` AS
SELECT c.campaign_id, c.campaign_name, c.event_name, c.total_budget,
       IFNULL(SUM(IF(l.entry_type = 'SPEND', l.amount, 0)), 0) AS spent,
       IFNULL(SUM(CASE l.entry_type WHEN 'COMMIT' THEN l.amount WHEN 'RELEASE' THEN -l.amount ELSE 0 END), 0) AS committed,
       c.total_budget
         - IFNULL(SUM(IF(l.entry_type = 'SPEND', l.amount, 0)), 0)
         - IFNULL(SUM(CASE l.entry_type WHEN 'COMMIT' THEN l.amount WHEN 'RELEASE' THEN -l.amount ELSE 0 END), 0) AS remaining
FROM `{project}.{dataset}.campaigns` c
LEFT JOIN `{project}.{dataset}.budget_ledger` l USING (campaign_id)
GROUP BY c.campaign_id, c.campaign_name, c.event_name, c.total_budget
;

CREATE OR REPLACE VIEW `{project}.{dataset}.v_request_headroom` AS
SELECT l.request_id,
       SUM(CASE l.entry_type WHEN 'COMMIT' THEN l.amount WHEN 'RELEASE' THEN -l.amount ELSE 0 END) AS approved,
       IFNULL(ANY_VALUE(p.ordered), 0) AS ordered
FROM `{project}.{dataset}.budget_ledger` l
LEFT JOIN (
  SELECT request_id, SUM(total_amount) AS ordered
  FROM `{project}.{dataset}.purchase_orders` WHERE status = 'CREATED' GROUP BY request_id
) p USING (request_id)
WHERE l.entry_type IN ('COMMIT', 'RELEASE')
GROUP BY l.request_id
;

