#!/usr/bin/env python3
"""Create the BigQuery dataset, tables, views and demo data for The Campaign Provisioner.

Examples
  python scripts/setup_bigquery.py --project my-proj                # create + seed (idempotent)
  python scripts/setup_bigquery.py --project my-proj --reset-demo   # clear demo transactions, keep reference data
  python scripts/setup_bigquery.py --project my-proj --reset        # drop everything and rebuild
  python scripts/setup_bigquery.py --print-ddl > bigquery/schema.sql  # DDL only, no GCP access needed
"""
import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from campaign_provisioner.data.schema import TABLES, TRANSACTION_TABLES, VIEWS  # noqa: E402
from campaign_provisioner.data.seed_data import SEED  # noqa: E402


def ddl(ds: str) -> str:
    out = [f"-- Generated by scripts/setup_bigquery.py --print-ddl. Replace {ds} with `project.dataset`.\n"]
    for name, t in TABLES.items():
        cols = ",\n".join(f"  {c} {typ}{' NOT NULL' if mode == 'REQUIRED' else ''}"
                          + (f" OPTIONS(description=\"{d}\")" if d else "") for c, typ, mode, d in t["columns"])
        out.append(f"CREATE TABLE IF NOT EXISTS `{ds}.{name}` (\n{cols}\n) OPTIONS(description=\"{t['description']}\");\n")
    for name, sql in VIEWS.items():
        out.append(f"CREATE OR REPLACE VIEW `{ds}.{name}` AS{sql.replace('{ds}', ds)};\n")
    return "\n".join(out)


def _json_rows(rows):
    return [{k: (v.isoformat() if isinstance(v, datetime) else v) for k, v in r.items()} for r in rows]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", default=os.getenv("GOOGLE_CLOUD_PROJECT"))
    ap.add_argument("--dataset", default=os.getenv("BQ_DATASET", "campaign_provisioner"))
    ap.add_argument("--location", default=os.getenv("BQ_LOCATION", "US"))
    ap.add_argument("--reset", action="store_true", help="drop all tables/views and rebuild with seed data")
    ap.add_argument("--reset-demo", action="store_true", help="clear demo transactions, keep reference data")
    ap.add_argument("--print-ddl", action="store_true", help="print CREATE statements and exit")
    args = ap.parse_args()

    if args.print_ddl:
        print(ddl("{project}.{dataset}"))
        return
    if not args.project:
        sys.exit("Set --project or GOOGLE_CLOUD_PROJECT")

    from google.cloud import bigquery

    client = bigquery.Client(project=args.project, location=args.location)
    ds = f"{args.project}.{args.dataset}"

    if args.reset_demo:
        for t in TRANSACTION_TABLES:
            client.query(f"TRUNCATE TABLE `{ds}.{t}`").result()
        client.query(f"DELETE FROM `{ds}.budget_ledger` WHERE request_id != 'BASELINE'").result()
        print(f"Demo transactions cleared in {ds}. Reference data and opening budgets untouched.")
        return

    dataset = bigquery.Dataset(ds)
    dataset.location = args.location
    client.create_dataset(dataset, exists_ok=True)
    print(f"Dataset {ds} ready ({args.location})")

    if args.reset:
        for v in VIEWS:
            client.delete_table(f"{ds}.{v}", not_found_ok=True)
        for t in TABLES:
            client.delete_table(f"{ds}.{t}", not_found_ok=True)

    for name, t in TABLES.items():
        table = bigquery.Table(f"{ds}.{name}", schema=[bigquery.SchemaField(c, typ, mode=mode, description=d)
                                                         for c, typ, mode, d in t["columns"]])
        table.description = t["description"]
        client.create_table(table, exists_ok=True)
        print(f"  table {name}")

    for name, sql in VIEWS.items():
        view = bigquery.Table(f"{ds}.{name}")
        view.view_query = sql.replace("{ds}", ds)
        client.delete_table(f"{ds}.{name}", not_found_ok=True)
        client.create_table(view)
        print(f"  view  {name}")

    for name, t in TABLES.items():
        rows = SEED.get(name, [])
        existing = next(iter(client.query(f"SELECT COUNT(*) n FROM `{ds}.{name}`").result()))["n"]
        if not rows or existing:
            continue
        cfg = bigquery.LoadJobConfig(
            schema=[bigquery.SchemaField(c, typ, mode=mode) for c, typ, mode, _ in t["columns"]],
            write_disposition="WRITE_APPEND")
        client.load_table_from_json(_json_rows(rows), f"{ds}.{name}", job_config=cfg).result()
        print(f"  loaded {len(rows):>3} rows into {name}")

    print("\nDone. Next: python scripts/verify_setup.py")


if __name__ == "__main__":
    main()
